In [98]:
# Import necessary libraries
import json
import pandas as pd


# Load the JSON file as a list of dictionaries
with open("C:\\Users\\Harsh\\interactive_Data\\chessbuds_messages.json") as b:
    C_M = json.load(b)

In [99]:
type(C_M)

C_M.keys()

dict_keys(['participants', 'messages', 'title', 'is_still_participant', 'thread_type', 'thread_path', 'magic_words', 'joinable_mode'])

In [100]:
# Display a subset 
C_M['messages'][0:2]

C_M['messages'][0].keys()

dict_keys(['sender_name', 'timestamp_ms', 'content', 'reactions', 'type', 'is_unsent', 'is_taken_down', 'bumped_message_metadata'])

In [101]:
# key information in the data

C_M['participants']

[{'name': 'Scott Pence'},
 {'name': 'Chad Larson'},
 {'name': 'Joanna Rusch'},
 {'name': 'Angela Babbitt Pence'},
 {'name': 'David Silva'},
 {'name': 'Aaron Rusch'},
 {'name': 'Timothy Vanderpool'}]

In [102]:
# Assuming your 'messages' data is stored in a variable called data
df = pd.DataFrame(C_M['messages'])

# Columns to drop
Drops_C = ['share', 'photos', 'gifs', 'users', 'reactions', 'is_unsent', 'is_taken_down', 'bumped_message_metadata']

# Drop specified columns
df_drop = df.drop(columns=Drops_C)

# Display the resulting DataFrame after dropping columns
df_drop

,sender_name,timestamp_ms,content,type
0,Joanna Rusch,1666374933946,Maybe he just wants to ride the publicity for ...,Generic
1,Chad Larson,1666373448613,To be fair to Hans....no one wants to be assoc...,Generic
2,Chad Larson,1666373216381,He would have to prove he didn't cheat and tha...,Generic
3,Scott Pence,1666373164883,"Yeah, no way. You over shoot and hope to get a...",Generic
4,Chad Larson,1666373111157,"From what I see, I don't think he could win. ...",Generic
...,...,...,...,...
218,Scott Pence,1615855643693,"Thank you, thank you.",Generic
219,Scott Pence,1615855620614,NaN,Generic
220,Chad Larson,1615854725212,Chad Larson added Angela Babbitt Pence to the ...,Subscribe
221,Chad Larson,1615854680797,"Scott studied my games, did a specific opening...",Generic
222,Chad Larson,1615854650355,Chad named the group Chess Buds.,Generic

In [103]:


# Group the DataFrame by multiple columns and count occurrences
grouped_df = df_drop.groupby(['type', 'sender_name', 'content', 'timestamp_ms']).size().reset_index(name='count')

# Display the resulting DataFrame with grouped counts
grouped_df

,type,sender_name,content,timestamp_ms,count
0,Generic,Aaron Rusch,How I feel play chess against you all.,1616196148462,1
1,Generic,Aaron Rusch,If only it were real...,1617337166358,1
2,Generic,Aaron Rusch,Thank you. I'm pretty sure I just played my be...,1617080283564,1
3,Generic,Angela Babbitt Pence,April fools??,1617336779230,1
4,Generic,Angela Babbitt Pence,My reaction to Scott's pun.,1622675473089,1
...,...,...,...,...,...
189,Share,Scott Pence,https://youtu.be/x-q64bPo0J0,1662513107863,1
190,Subscribe,Chad Larson,Chad Larson added Angela Babbitt Pence to the ...,1615854725212,1
191,Subscribe,Scott Pence,Scott Pence added you to the group.,1619913094621,1
192,Subscribe,Scott Pence,Scott Pence added you to the group.,1619984216568,1
193,Unsubscribe,David Silva,You left the group.,1619984147883,1

## Description on row level observation 

**sender_name** name of sender of the messages\
**timestamp_ms** Timestamp in milliseconds \
**content** Messages stored on the data \
**reactions** reactions on the messages \
**type** classification of the message types\
**is_unsent** status of the message sof unsent\
**is_taken_down** status of the messages if they have been tajen down or not, majority of the cases shoe false in case\
**bumped_message_metadata** Metadata of the messages that are stored\
**share** message sharing information, how were the messages shared \
**photos** pictures that are availabele  with the message. If there is no photo available then it will be empty.\
**gifs** gifs that were incliuded or are part of the messgaes\
**users:** user information on stored data

## The Data frame meets the tidy requirements 

All Variables are stored in seperate columns\
No missing data is present.\
Each row of the dataset represent a unique observation or case.\
Clear and consise column headings\
Also the data frame doesnot contain dupicasises\
Hense the data frame meets the tidy requirements

## Other tidy formats 
Other tidy formats include to seggrigare the picture formats and reaction and media contect to a different tables.\
including time specific data in seperate tables and converting time stamps to date time format.\
Structure the messages table to better understand  the communication between users. This will allow for easier analysis of user interactions, such as frequency of interaction.

## Vizual representation

Use of bar charts to represent the  data representing different reactions.
line  chart can be used for time series analysis, to understand the frequency of the messages  over a period of time. Bar charts are more suitable for categorical data.
visuals like these would let users slice the conversation data in various ways to extract insights and make decisions based on that information.